name: 'First Example Workflow'

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: List and Read file ReadMe
          run: | 
            echo 'Hello, welcome to your first GitHub Actions workflow!'
            ls -la
            cat README.md

        # - name: List Files
        #   run: ls -la
        # - name: Read File
        #   run: cat README.md