name: 'First Example Workflow'


on: push


jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Execute shell script
          run: |
            chmod +x ./scripts/workflow-script.sh
            ./scripts/workflow-script.sh

    second-job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Execute shell script
          run: |
            chmod +x ./scripts/workflow-script.sh
            ./scripts/workflow-script.sh


    third-job:
        concurrency:
            group: 'third-job-group'
            cancel-in-progress: false
        runs-on: ubuntu-latest
        needs: second-job
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Execute shell script
          run: |
            chmod +x ./scripts/workflow-script.sh
            ./scripts/workflow-script.sh
        - name : Pause for 100 seconds
          run : sleep 100s
        
          #Test 4